name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'  # Executa o workflow para tags que seguem o padrão de versão semântica

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          registry: "https://npm.pkg.github.com"
        
