name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'  # Executa o workflow para tags que seguem o padr찾o de vers찾o sem창ntica

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - run: npm ci
        - run: npm test
      
  publish:
    needs: build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18  # Use a vers찾o mais recente do Node.js
          registry: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
        

        
